### ISSUE TITLE
Bootable?

### ISSUE THREAD

**Issue by jordan89m** [dabao1955/pmos_xiaomi_raphael#1]
Is this able to boot? If so, are there any special steps in the current state of this repo?

I flashed rootfs using --partition userdata but boot goes to a black screen.

Been waiting for a project like this for so long! I don't do android dev stuff much but I'll chip in wherever I can to help get this up and running.

**Comment by dabao1955** [comment]
Hello, thank you for your reply.
To be honest, since I don’t have the equipment on hand, it will always be a work-in-progress until I have the equipment to debug it.
Based on your reply, have you flashed boot.img? If flashed, have you cleared the dtbo partition? If you have done all of the above, it may be a kernel problem. Sorry, I don't have much time to check where the problem is, please understand.

**Comment by jordan89m** [comment]
Yeah, I did this: pmbootstrap flasher flash_rootfs --partition userdata, fastboot erase dtbo, pmbootstrap flasher flash_kernel, then pmbootstrap flasher boot.

**Comment by jordan89m** [comment]
I'm no pmos guru either, so if theres a way to get you any certain logs, let me know!

**Comment by jordan89m** [comment]
Should I flash the boot img just using fastboot instead? Or perhaps pmbootstrap install --split?

**Comment by jordan89m** [comment]
I'm going to port Jumpdrive (https://github.com/dreemurrs-embedded/Jumpdrive) for the K20 Pro. I think this is going to be needed to make it work. It was the only way I ever got things working smoothly on Poco F1. I'll keep you updated!

**Comment by dabao1955** [comment]
> Yeah, I did this: pmbootstrap flasher flash_rootfs --partition userdata, fastboot erase dtbo, pmbootstrap flasher flash_kernel, then pmbootstrap flasher boot.

Hello sir:
I saw your reply and I think this may require clearing deviceinfo's cmdline. In addition, I don't have a good method because I don't have debugging equipment on hand, please understand.

**Comment by dabao1955** [comment]
or do not erase dtbo partition？

**Comment by jordan89m** [comment]
I got it booting! required a little tweak to kernel APKBUILD as well as overhaul of deviceinfo. Problem now is that gnome-mobile starts briefly then crashes, then it drops to TTY then goes black screen.

**Comment by dabao1955** [comment]
> I got it booting! required a little tweak to kernel APKBUILD as well as overhaul of deviceinfo. Problem now is that gnome-mobile starts briefly then crashes, then it drops to TTY then goes black screen.

Hello sir,
Very happy to hear such news.
You can use xfce instead of gnome. I think this is because the gpu driver is not very stable yet.
Also I'd like to know how you fixed it and if so could you submit a pull request?

**Comment by dabao1955** [comment]
Hello sir.
Since you haven't replied to me, I tried changing the deviceinfo according to the device tree of Xiaomi Mi Pad 5. You can try to see if it can be booted. @jordan89m 

https://github.com/dabao1955/pmos_xiaomi_raphael/commit/ce3d558dd8537932075f4a30b8dc0aa70077e9bf

**Comment by baso53** [comment]
I can try to flash @dabao1955  , but I have a phone with a broken screen, so I might not be able to verify it.

Can I ask if there's a reason to use Mi Pad 5 for the base instead of Mi 9? Mi 9 even has Snapdragon 855, instead of 860 in Mi Pad 5.

**Comment by dabao1955** [comment]
> I can try to flash @dabao1955 , but I have a phone with a broken screen, so I might not be able to verify it.
> 
> Can I ask if there's a reason to use Mi Pad 5 for the base instead of Mi 9? Mi 9 even has Snapdragon 855, instead of 860 in Mi Pad 5.

Uh, okay. I just think that the Xiaomi Mi Pad 5 SOC can basically be regarded as an overclocked Snapdragon 855 and I happened to find the repository on github.

Now I fixed it on 1b8a785

@jordan89m  @baso53

**Comment by baso53** [comment]
Could you explain shortly how can I build the rootfs and kernel for this repository? I didn't work with custom repos. @dabao1955

**Comment by dabao1955** [comment]
> Could you explain shortly how can I build the rootfs and kernel for this repository? I didn't work with custom repos. @dabao1955

Please execute 
pmbootstrap checksum linux-xiaomi-rapheal pmbootatrap build linux-xiaomi-raphael pmbootstrap install
 after the initialization is completed.

**Comment by baso53** [comment]
I didn't manage to boot neither the 23.06 or 23.06-dev branch @dabao1955 . I just get into fastboot again.

But, one thing I tried is to flash the mainline kernel of Mi 9 (xiaomi-cepheus) with the instructions from [here](https://wiki.postmarketos.org/wiki/Xiaomi_Mi_9_(xiaomi-cepheus)#Installation), and it actually succeded to boot. I can ping the device at 172.16.42.1 and the USB networking seems to be working, but SSH doesn't work, so that's the farthest I managed to get. I would say that UFS is not working, which is the same problem that Mi 9 has.

**Comment by dabao1955** [comment]
> I didn't manage to boot neither the 23.06 or 23.06-dev branch @dabao1955 . I just get into fastboot again.
> 
> But, one thing I tried is to flash the mainline kernel of Mi 9 (xiaomi-cepheus) with the instructions from [here](https://wiki.postmarketos.org/wiki/Xiaomi_Mi_9_(xiaomi-cepheus)#Installation), and it actually succeded to boot. I can ping the device at 172.16.42.1 and the USB networking seems to be working, but SSH doesn't work, so that's the farthest I managed to get. I would say that UFS is not working, which is the same problem that Mi 9 has.

I have a question, do you mean you flashed the mainline kernel of mi9 or the raphael mainline kernel according to the mi9 mainline kernel flashing method? If it is the former, I think there is a high probability that it may be a kernel or dtb problem.

**Comment by dabao1955** [comment]
@jordan89m Are you still there?

**Comment by baso53** [comment]
> > I didn't manage to boot neither the 23.06 or 23.06-dev branch @dabao1955 . I just get into fastboot again.
> > But, one thing I tried is to flash the mainline kernel of Mi 9 (xiaomi-cepheus) with the instructions from [here](https://wiki.postmarketos.org/wiki/Xiaomi_Mi_9_(xiaomi-cepheus)#Installation), and it actually succeded to boot. I can ping the device at 172.16.42.1 and the USB networking seems to be working, but SSH doesn't work, so that's the farthest I managed to get. I would say that UFS is not working, which is the same problem that Mi 9 has.
> 
> I have a question, do you mean you flashed the mainline kernel of mi9 or the raphael mainline kernel according to the mi9 mainline kernel flashing method? If it is the former, I think there is a high probability that it may be a kernel or dtb problem.

The former. Do you have some steps to proceed?

**Comment by dabao1955** [comment]
No, I don't think there's anything wrong with it. But I still have some doubts. Maybe I didn’t explain it clearly. Is it the mainline of mi9 or the mainline of Raphael?

**Comment by baso53** [comment]
> No, I don't think there's anything wrong with it. But I still have some doubts. Maybe I didn’t explain it clearly. Is it the mainline of mi9 or the mainline of Raphael?

Mainline Mi 9.

**Comment by dabao1955** [comment]
> > No, I don't think there's anything wrong with it. But I still have some doubts. Maybe I didn’t explain it clearly. Is it the mainline of mi9 or the mainline of Raphael?
> 
> Mainline Mi 9.

OK, thanks for your reply.
So have you modified deviceinfo? Or just modified the url of the kernel source code?

**Comment by baso53** [comment]
> > > No, I don't think there's anything wrong with it. But I still have some doubts. Maybe I didn’t explain it clearly. Is it the mainline of mi9 or the mainline of Raphael?
> > 
> > 
> > Mainline Mi 9.
> 
> OK, thanks for your reply. So have you modified deviceinfo? Or just modified the url of the kernel source code?

Not even that. I straight up installed like I would install if I had a Mi 9.

```
pmbootstrap init -> xiaomi -> cepheus
fastboot erase dtbo
pmbootstrap flasher flash_vbmeta
pmbootstrap flasher flash_rootfs
pmbootstrap flasher flash_kernel
```

For this process, I didn't use any code from this repository. I hope it helps.

**Comment by dabao1955** [comment]
> > > > No, I don't think there's anything wrong with it. But I still have some doubts. Maybe I didn’t explain it clearly. Is it the mainline of mi9 or the mainline of Raphael?
> > > 
> > > 
> > > Mainline Mi 9.
> > 
> > 
> > OK, thanks for your reply. So have you modified deviceinfo? Or just modified the url of the kernel source code?
> 
> Not even that. I straight up installed like I would install if I had a Mi 9.
> 
> ```
> pmbootstrap init -> xiaomi -> cepheus
> fastboot erase dtbo
> pmbootstrap flasher flash_vbmeta
> pmbootstrap flasher flash_rootfs
> pmbootstrap flasher flash_kernel
> ```
> 
> For this process, I didn't use any code from this repository. I hope it helps.

Well, it seems that I will continue this work when I have the equipment to debug. Anyway, thanks for your reply. However, I feel that although the soc is the same, the configuration files should not be mixed.
