### ISSUE TITLE
Now it bootable？

### ISSUE THREAD

**Issue by dabao1955** [dabao1955/pmos_xiaomi_raphael#3]
Hey guys.

I just fixed the deviceinfo related dtb part of this device tree based on the upstream Xiaomi 9's PostmarketOS device tree, and now it should build and boot the rootfs successfully.

If the device boots after this repair , please let me know immediately. I think I'll be happy.

**Comment by jordan89m** [comment]
![IMG20240311140300-min](https://github.com/dabao1955/pmos_xiaomi_raphael/assets/59252806/16cd44b1-dcc2-4670-9afe-6015d95b7cbe)

your latest commit boots to xfce4. BUT no buttons, touchscreen doesnt respond and usb net device for ssh dont work.

PROGRESS! 💯

**Comment by jordan89m** [comment]
update: volume buttons work! lock doesnt. must be xfce.

**Comment by dabao1955** [comment]
> update: volume buttons work! lock doesnt. must be xfce.

Is the type of screen panel of your device a goodix model?
